version: '2'
services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
      - "28017:27017"
  mysql:
    build: ./mysql
    ports:
      - "${SAMPLE_DOCKER_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:3.2
    ports:
      - "${SAMPLE_DOCKER_REDIS_PORT}:6379"


