version: '2'
services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
      - "28017:27017"
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  resque-web:
    build: ./resque-web
    ports:
      - "5678:5678"
    depends_on:
      - "redis"
    command: -r redis:6379



