default: &default
  adapter: mysql2
  encoding: utf8
  host: 192.168.100.12
  username: root
  password:
  pool: 5
  timeout: 5000
  database: sample

development:
  <<: *default
  database: sample

test:
  <<: *default
  database: sample

production:
  <<: *default
  database: sample

