default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: 192.168.30.84
  username: root
  password:
  pool: 5
  timeout: 5000
  database: sample
  host: <%= ENV['SAMPLE_DOCKER_MYSQL_HOST'] || '127.0.0.1' %>
  port: <%= ENV['SAMPLE_DOCKER_MYSQL_PORT'] || '3306' %>

development:
  <<: *default
  database: sample

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample
  host: production-host

