default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: 192.168.30.84
  username: root
  password:
  pool: 5
  timeout: 5000
  database: sample

development:
  <<: *default
  database: sample

test:
  <<: *default
  database: sample

production:
  <<: *default
  database: sample

