default: &default
  host: <%= ENV['SAMPLE_DOCKER_REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['SAMPLE_DOCKER_REDIS_PORT'] || '6379' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: production-host
